vim.g.linefly_options = {
  separator_symbol = "⎪",
  progress_symbol = "↓",
  active_tab_symbol = "▪",
  git_branch_symbol = "",
  error_symbol = "E",
  warning_symbol = "W",
  information_symbol = "I",
  tabline = false,
  winbar = false,
  with_file_icon = false,
  with_git_branch = false,
  with_git_status = false,
  with_diagnostic_status = true,
  with_session_status = false,
  with_indent_status = true,
}
